# Generated by Django 4.2 on 2023-04-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar_laptop',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='registrar_laptop',
            name='grafica',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registrar_laptop',
            name='marca',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registrar_laptop',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registrar_laptop',
            name='procesador',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='registrar_laptop',
            name='teclado',
            field=models.CharField(max_length=10),
        ),
    ]
