# Generated by Django 4.2 on 2023-04-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_alter_registrar_laptop_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar_laptop',
            name='color',
            field=models.CharField(max_length=15),
        ),
    ]
