# Generated by Django 4.2 on 2023-04-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_alter_registrar_laptop_imagenes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrar_laptop',
            old_name='imagenes',
            new_name='imagen_1',
        ),
        migrations.AddField(
            model_name='registrar_laptop',
            name='imagen_2',
            field=models.ImageField(null=True, upload_to='proyecto/static/imagenes'),
        ),
        migrations.AddField(
            model_name='registrar_laptop',
            name='imagen_3',
            field=models.ImageField(null=True, upload_to='proyecto/static/imagenes'),
        ),
        migrations.AddField(
            model_name='registrar_laptop',
            name='imagen_4',
            field=models.ImageField(null=True, upload_to='proyecto/static/imagenes'),
        ),
    ]
