# Generated by Django 4.1.1 on 2023-04-27 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_vender_laptop'),
    ]

    operations = [
        migrations.DeleteModel(
            name='vender_Laptop',
        ),
    ]
