# Generated by Django 4.1.1 on 2023-04-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_delete_vender_laptop'),
    ]

    operations = [
        migrations.CreateModel(
            name='vender_Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20, unique=True)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('fecha', models.DateField()),
                ('cliente', models.CharField(max_length=35)),
                ('direccion', models.CharField(max_length=25)),
                ('ci', models.IntegerField()),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
