# Generated by Django 4.1.1 on 2023-05-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0011_registrar_usuarios'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registrar_usuarios',
        ),
    ]
