# Generated by Django 4.2 on 2023-04-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrar_Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('stock', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('pantalla', models.CharField(choices=[('13pulg', '13 pulgadas'), ('14pulg', '14 pulgadas'), ('15.6pulg', '15.6 pulgadas'), ('17pulg', '17 pulgadas')], max_length=10)),
                ('teclado', models.CharField(max_length=10, unique=True)),
                ('procesador', models.CharField(max_length=25, unique=True)),
                ('ram', models.CharField(choices=[('2', '2gb'), ('2exp', '2gb(exp)'), ('4', '4gb'), ('4exp', '4gb(exp)'), ('8', '8gb'), ('8exp', '8gb(exp)'), ('16', '16gb'), ('16exp', '16gb(exp)'), ('32', '32gb'), ('32xp', '32gb(exp)')], max_length=10)),
                ('color', models.CharField(max_length=15, unique=True)),
                ('m2', models.CharField(choices=[('256gb', '256 gb'), ('512gb', '512 gb'), ('1tb', '1 tb'), ('2tb', '2 tb')], max_length=10)),
                ('hdd', models.CharField(choices=[('sinhdd', 'sin HDD'), ('256hdd', '256 gb'), ('512hdd', '512 gb'), ('1hdd', '1 tb'), ('2hdd', '2 tb')], max_length=10)),
                ('grafica', models.CharField(max_length=25, unique=True)),
                ('descripcion', models.CharField(max_length=1000, unique=True)),
                ('imagenes', models.ImageField(null=True, upload_to='imagenes/productos')),
            ],
        ),
    ]
