# Generated by Django 4.2 on 2023-04-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_alter_registrar_laptop_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrar_laptop',
            name='imagenes',
            field=models.ImageField(null=True, upload_to='proyecto/static/imagenes'),
        ),
    ]
